source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GlyuckDataGrid_Example' do
  pod "GlyuckDataGrid", :path => "../"
end

target 'GlyuckDataGrid_Tests' do
  pod "GlyuckDataGrid", :path => "../"


end
